language: node_js
node_js:
- "4.1"
before_install:
- cd web
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm cache clean
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAABAQDuXJVzL5DXT9c4+71Ax76JopYDM4ZfmThOqO0wRFLKeQCo/Y8abWpQ20629oLTDCkFecDrcDMEglvXbULwMRVNFqMERrX2EHrX+WayMMmdOmlBbNhgoNHfvWzl3bKPpIVJQxG9ZO4GuiDgo9Y8N0R9YRmuKXNwcDVeOKZ2nADcUGG3+O42Fb7aUZQ+aeNCBaCFfDPxQZWKZz3UhZWUCuvJwdDXGdlX0ysqBbFkQhDiZ3Jo7P278ucMwY9twcRknGhVKN0WIhao/lPatirwxO8W38YvSuO2/pak8S12KELabQ1HAu0OBWRSJ2hY4ZU+FhpQfZG6ZDbcDohf5u0KJ7sP
  app: ondetemjogo
  on:
    repo: ondetemjogo/ondetemjogo
